---
apiVersion: apps/ v1

kind: ReplicaSet

metadata:
  name: myapp-pod
  labels:
    app: myapp

spec:
  containers:
    - name: nginx-container
      image: nginx
    - name: backend
      image: redis
